# Generated by Django 4.0.2 on 2022-03-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='file',
            field=models.FileField(upload_to='plugins/'),
        ),
    ]
