# Generated by Django 4.0.2 on 2022-03-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_plugin_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
