# Generated by Django 4.0.2 on 2022-03-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_plugin_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
