# Generated by Django 4.0.3 on 2022-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_plugin_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='author',
            field=models.CharField(default='Muhammad Saad', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugin',
            name='entry',
            field=models.CharField(default='main/', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugin',
            name='version',
            field=models.FloatField(default=1.0),
        ),
    ]
