# Generated by Django 4.0.3 on 2022-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_plugin_author_alter_plugin_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
